### ISSUE TITLE
The words are on top of the red accent part of the page

### ISSUE THREAD

**Issue by theapplegates** [mattdecamp/eleventonia#2]
I feel like my Dad putting the whole problem in the subject line.
A screenshot will better explain the problem.
![IMG_22C9B5D3AC3B-1](https://user-images.githubusercontent.com/27178137/148073325-fadf2385-89d1-464f-ae21-ecbce8366814.jpeg)

As you can see the text flows into the red accent color. This is on an iPhone in Safari & Chrome.
Can this be fixed? 
Thanks for your time.
Paul

**Comment by mattdecamp** [comment]
Hey, Paul!
Believe it or not, that is by design. It's a simple [linear-gradient effect](https://github.com/mattdecamp/eleventonia/blob/main/src/assets/styles/base/_layout.scss) on the background of the page. You are welcome to take that right out of your design. Or if you are trying to keep it, you could even try utilizing [`shape-outside` and `shape-image-threshold`](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-image-threshold) to adapt text shape and screen size, etc.
Matt

**Comment by theapplegates** [comment]
Sorry for the late reply. 
Thanks for the info, I had no idea. Looking at my screen shot, it looks better now. I'm sure it was all in my mind. Thanks for the facts.
